name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node: 14.4.0-stretch
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.18.0-stretch
        with:
          entrypoint: '/bin/echo'
          args: 'Hello world'
      - name: Log node version
        uses: docker://node:12.18.0-stretch
        with:
          entrypoint: /usr/local/bin/node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports: 
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: >
          curl -X POST http://localhost:3001/api/user -H 
          'Content-Type: application/json' -d 
          '{"username":"hello","address":"dsadsadsa"}'
      - name: Get Users
        run: curl http://localhost:3001/api/users
