name: Matrix

on: push

jobs:
  node_version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node_version: [8, 10, 12]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version from matrix
        run: node -v